// This file contains build-time information
// Auto-generated by: pnpm update:version

export const environment = {
  production: false,
  version: 'undefined',
  gitCommit: '7fc5c8b',
  defaultLanguage: (globalThis as any).DEFAULT_LANGUAGE || null,
};
