// This file contains build-time information
// Auto-generated by: pnpm update:version

export const environment = {
  production: false,
  version: '1.7.2',
  gitCommit: 'df9643b',
  defaultLanguage: (globalThis as any).DEFAULT_LANGUAGE || null,
};
