// This file contains build-time information
// Auto-generated by: pnpm update:version

export const environment = {
  production: false,
  version: '1.6.0',
  gitCommit: 'ea8ffdc',
  defaultLanguage: (globalThis as any).DEFAULT_LANGUAGE || null,
};
