[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/run/supervisord.pid
logfile_maxbytes=5MB

[program:api]
command=node /home/pptruser/app/dist/src/main.js
directory=/home/pptruser/app
user=pptruser
autostart=true
autorestart=true
stdout_logfile=/home/pptruser/app/logs/api.stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=1
stderr_logfile=/home/pptruser/app/logs/api.stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=1
redirect_stderr=false
environment=NODE_ENV="production"

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/home/pptruser/app/logs/nginx.stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=1
stderr_logfile=/home/pptruser/app/logs/nginx.stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=1
redirect_stderr=false
