/**
 * Updates the Angular environment file with the current version and git commit.
 * Called via `pnpm update:version` (prebuild hook).
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const rootPackageJson = JSON.parse(
  fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf-8'),
);
const version = rootPackageJson.version || 'unknown';

let gitCommit = 'unknown';
try {
  gitCommit = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
} catch {
  // Not a git repo or git not available
}

const environmentPath = path.join(
  __dirname,
  '..',
  'apps',
  'ui',
  'src',
  'environments',
  'environment.ts',
);

const content = `// This file contains build-time information
// Auto-generated by: pnpm update:version

export const environment = {
  production: false,
  version: '${version}',
  gitCommit: '${gitCommit}',
  defaultLanguage: (globalThis as any).DEFAULT_LANGUAGE || null,
};
`;

fs.writeFileSync(environmentPath, content, 'utf-8');
console.log(`Updated environment.ts: version=${version}, gitCommit=${gitCommit}`);
