/**
 * Updates the Angular environment file with the current version and git commit hash.
 * Called automatically via `pnpm update:version` (prebuild hook).
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const envFilePath = path.join(
  __dirname,
  '..',
  'apps',
  'ui',
  'src',
  'environments',
  'environment.ts',
);

// Read version from package.json
const packageJson = JSON.parse(
  fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'),
);
const version = packageJson.version || 'unknown';

// Get current git commit hash (env var takes precedence for Docker/CI builds)
let gitCommit = process.env.GIT_COMMIT || 'unknown';
if (gitCommit === 'unknown') {
  try {
    gitCommit = execSync('git rev-parse --short HEAD').toString().trim();
  } catch {
    console.warn('Could not determine git commit hash');
  }
}

const content = `// This file contains build-time information
// Auto-generated by: pnpm update:version

export const environment = {
  production: false,
  version: '${version}',
  gitCommit: '${gitCommit}',
  defaultLanguage: (globalThis as any).DEFAULT_LANGUAGE || null,
};
`;

fs.writeFileSync(envFilePath, content, 'utf8');
console.log(`Updated environment.ts: version=${version}, commit=${gitCommit}`);
