name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'apps/docs/**'
      - '**/*.md'

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    needs: test
    uses: ./.github/workflows/release.yml
    secrets: inherit

  docker:
    name: Docker
    needs: release
    if: needs.release.outputs.new_release_published == 'true'
    uses: ./.github/workflows/docker.yml
    with:
      version: ${{ needs.release.outputs.new_release_version }}
    secrets: inherit
