name: 'Contributors'

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: contrib-rocks/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit contributors image
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff --staged --quiet || git commit -m "docs: update contributors [skip ci]"
          git push
